spring:
  application:
    name: profile-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/it_mentor_community_platform?currentSchema=profile_service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest
    topic:
      projects-project-created: projects.project.created
      auth-user-created: auth.user.created

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

profile-service:
  achievements:
    FIRST_PROJECT: Сдан первый проект!
    ALL_PROJECTS: Сданы все проекты!
    BILINGUAL: Сданы проекты на двух языках!
    POLYGLOT: Сданы проекты на 4+ языках!
    SPRINTER: Сданы с 1 по 6 проект за 6 месяцев!



